### ISSUE TITLE
"spectre_client.gemspec is not valid. Please fix this gemspec."

### ISSUE THREAD

**Issue by mansn** [wearefriday/spectre_client#7]
This is actually an issue I encountered when trying to run [wearefriday/spectre](https://github.com/wearefriday/spectre) with docker.

```
λ docker-compose run --rm app bundle exec rake db:setup
Starting spectre_db_1 ... done
Building app
Step 1/11 : FROM ruby:2.3
 ---> 03ff8cebf24f
Step 2/11 : WORKDIR /opt
 ---> Using cache
 ---> 82416337d43c
Step 3/11 : RUN curl -Ls https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 | tar -jxf -
 ---> Using cache
 ---> 4da6451b21e8
Step 4/11 : RUN apt-get -qq update && apt-get -qq install fontconfig
 ---> Using cache
 ---> 9e7c40c3d44e
Step 5/11 : RUN ln -s /opt/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin/
 ---> Using cache
 ---> fe378b173a61
Step 6/11 : WORKDIR /app
 ---> Using cache
 ---> c06d1f98a986
Step 7/11 : ADD Gemfile* /app/
 ---> Using cache
 ---> 124d4525897b
Step 8/11 : RUN gem install bundler && bundle config build.nokogiri --use-system-libraries && bundle install --quiet --jobs 16 --retry 5 --without test
 ---> Running in cab7c0c91eec
Successfully installed bundler-1.16.1
1 gem installed
The gemspec at
/usr/local/bundle/bundler/gems/spectre_client-a83cbca5f054/spectre_client.gemspec
is not valid. Please fix this gemspec.
The validation error was '"TODO: Put your gem's website or public repo URL
here." is not a valid HTTP URI'
ERROR: Service 'app' failed to build: The command '/bin/sh -c gem install bundler && bundle config build.nokogiri --use-system-libraries && bundle install --quiet --jobs 16 --retry 5 --without test' returned a non-zero code: 1
```
After reading about this ([here](https://github.com/bundler/bundler/issues/3781), [here](https://github.com/kitcheck/life_guard/pull/4) and [here](http://guides.rubygems.org/specification-reference/)), it seems that there needs to be a valid URI here:
https://github.com/wearefriday/spectre_client/blob/f2bca77452ba584d342cf877d322928810f4fef7/spectre_client.gemspec#L14
and here:
https://github.com/wearefriday/spectre_client/blob/f2bca77452ba584d342cf877d322928810f4fef7/spectre_client.gemspec#L20

However, I don't get this issue when just cloning this repo and run bundle install.. which is weird? I've tried with the same version of bundler (1.16.1).

**Comment by nemasket** [comment]
I encountered this issue when using 'bundle gem $projectname'.  Tutorials recommend this approach for creating a gem so it seemed straightforward.   Running rake against the generated code fails on validations of metadata.    As mentioned above these validations are important to Rubygems.  Visiting the Rubygems site, they recommend metadata but don't require it.  

As generated, the gemspec file created by bundle tests:  'if spec.respond_to?(:metadata)'  before validating the various metadata entries.  Because the spec responds with an empty hash, the validations in the following block are assigned and subsequently validated.   As generated they will fail.  

The test for whether metadata is present needs to be different to avoid the validations.

Aside from the issues listed above, this could be off-putting to newcomers just finding their way.

**Comment by Firefishy** [comment]
Unfortunately no longer being maintained. Please follow up with one of the active forks.
